name: Tests

on:
  push:
    branches:
      - main
      - release-*
  pull_request:
    branches:
      - main
      - release-*

defaults:
  run:
    shell: bash

jobs:
  test:
    name: Test Setup ORAS CLI
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        version:
          - 0.15.0
          - 0.16.0
      fail-fast: true
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup ORAS v${{ matrix.version }}
      uses: ./
      with:
        version: ${{ matrix.version }}

    - name: Verify ORAS version installed
      env:
        ORAS_VERSION_EXPECTED: ${{ matrix.version }}
      run: |
        echo ---
        oras version
        echo ---
        read -ra ORAS_VERSION_INSTALLED <<<$(oras version)
        [ "${ORAS_VERSION_INSTALLED[1]}" == "ORAS_VERSION_EXPECTED" ]
